<?php

require_once 'components/page.php';
require_once 'components/security/datasource_security_info.php';
require_once 'components/security/security_info.php';
require_once 'components/security/hardcoded_auth.php';
require_once 'components/security/user_grants_manager.php';

include_once 'components/security/user_identity_storage/user_identity_session_storage.php';

$users = array('admin' => 'admin818');

$usersIds = array('admin' => -1);

$dataSourceRecordPermissions = array();

$grants = array('guest' => 
        array()
    ,
    'defaultUser' => 
        array('ecocrop' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_ID' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Agroecology' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Agronomic_Practices' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Cropping_System' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Fertiliser' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Pathology' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Resist_Tolerance' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Season' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Output' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Proximate' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Thermogravimetric' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Ulitmate' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Uses' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Composition' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Minerals' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Vitamins' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Growth_Cycle' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Growth_Habit' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Parts' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Parts_Used' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Type' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Usage' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Human' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Infrastructure' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Market' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Price' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Subsidy' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Water_Source' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Agroecology' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Agronomic_Practices' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Cropping_System' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Fertiliser' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Pathology' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Resist_Tolerance' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Season' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Aquacrop' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Output' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Proximate' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Thermogravimetric' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Ulitmate' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Uses' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_CRO_File' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Diseases' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Germplasm' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Institute' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Local_Name' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Pests' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Stat' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Synonyms' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_TTSR' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Vernacular_Name' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Weeds' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Where_Researched' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Where_UnderUtilised' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Composition' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Minerals' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Vitamins' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Preparation' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Growth_Cycle' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Growth_Habit' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Parts' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Parts_Used' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Type' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Usage' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Authors' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Country_LatLong' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Diseasess' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_GeoNames' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Institute' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Parts_ID' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Pests' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Weeds' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_localname_trial' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Metadata' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Accuracy' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Geo' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Images' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Notes' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_References' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Human' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Infrastructure' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Market' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Price' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Subsidy' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Water_Source' => new DataSourceSecurityInfo(false, false, false, false))
    ,
    'guest' => 
        array('ecocrop' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_ID' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Agroecology' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Agronomic_Practices' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Cropping_System' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Fertiliser' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Pathology' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Resist_Tolerance' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Season' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Output' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Proximate' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Thermogravimetric' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Ulitmate' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Uses' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Composition' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Minerals' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Vitamins' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Growth_Cycle' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Growth_Habit' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Parts' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Parts_Used' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Type' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Usage' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Human' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Infrastructure' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Market' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Price' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Subsidy' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Water_Source' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Agroecology' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Agronomic_Practices' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Cropping_System' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Fertiliser' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Pathology' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Resist_Tolerance' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Season' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Aquacrop' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Output' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Proximate' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Thermogravimetric' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Ulitmate' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Uses' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_CRO_File' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Diseases' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Germplasm' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Institute' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Local_Name' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Pests' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Stat' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Synonyms' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_TTSR' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Vernacular_Name' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Weeds' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Where_Researched' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Where_UnderUtilised' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Composition' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Minerals' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Vitamins' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Preparation' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Growth_Cycle' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Growth_Habit' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Parts' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Parts_Used' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Type' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Usage' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Authors' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Country_LatLong' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Diseasess' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_GeoNames' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Institute' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Parts_ID' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Pests' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Weeds' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_localname_trial' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Metadata' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Accuracy' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Geo' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Images' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Notes' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_References' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Human' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Infrastructure' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Market' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Price' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Subsidy' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Water_Source' => new DataSourceSecurityInfo(false, false, false, false))
    ,
    'admin' => 
        array('ecocrop' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_ID' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Agroecology' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Agronomic_Practices' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Cropping_System' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Fertiliser' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Pathology' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Resist_Tolerance' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Agro_Season' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Output' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Proximate' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Thermogravimetric' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Ulitmate' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Biomass_Uses' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Composition' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Minerals' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_Food_Nutrient_Vitamins' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Growth_Cycle' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Growth_Habit' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Parts' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Parts_Used' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Type' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_General_Usage' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Human' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Infrastructure' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Market' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Price' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Subsidy' => new DataSourceSecurityInfo(false, false, false, false),
        'Info_KBS_SocioEconomy_Water_Source' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Agroecology' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Agronomic_Practices' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Cropping_System' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Fertiliser' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Pathology' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Resist_Tolerance' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Agro_Season' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Aquacrop' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Output' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Proximate' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Thermogravimetric' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Ulitmate' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Biomass_Uses' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_CRO_File' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Diseases' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Germplasm' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Institute' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Local_Name' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Pests' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Stat' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Synonyms' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_TTSR' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Vernacular_Name' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Weeds' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Where_Researched' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Crop_Where_UnderUtilised' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Composition' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Minerals' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Nutrient_Vitamins' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Food_Preparation' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Growth_Cycle' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Growth_Habit' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Parts' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Parts_Used' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Type' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_General_Usage' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Authors' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Country_LatLong' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Diseasess' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_GeoNames' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Institute' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Parts_ID' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Pests' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Global_Weeds' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_localname_trial' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Metadata' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Accuracy' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Geo' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Images' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_Notes' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_Parameter_References' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Human' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Infrastructure' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Market' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Price' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Subsidy' => new DataSourceSecurityInfo(false, false, false, false),
        'KBS_SocioEconomy_Water_Source' => new DataSourceSecurityInfo(false, false, false, false))
    );

$appGrants = array('guest' => new DataSourceSecurityInfo(false, false, false, false),
    'defaultUser' => new DataSourceSecurityInfo(true, false, false, false),
    'guest' => new DataSourceSecurityInfo(false, false, false, false),
    'admin' => new AdminDataSourceSecurityInfo());

$tableCaptions = array('ecocrop' => 'Ecocrop',
'Info_ID' => 'Info ID',
'Info_KBS_Agro_Agroecology' => 'Info KBS Agro Agroecology',
'Info_KBS_Agro_Agronomic_Practices' => 'Info KBS Agro Agronomic Practices',
'Info_KBS_Agro_Cropping_System' => 'Info KBS Agro Cropping System',
'Info_KBS_Agro_Fertiliser' => 'Info KBS Agro Fertiliser',
'Info_KBS_Agro_Pathology' => 'Info KBS Agro Pathology',
'Info_KBS_Agro_Resist_Tolerance' => 'Info KBS Agro Resist Tolerance',
'Info_KBS_Agro_Season' => 'Info KBS Agro Season',
'Info_KBS_Biomass_Output' => 'Info KBS Biomass Output',
'Info_KBS_Biomass_Proximate' => 'Info KBS Biomass Proximate',
'Info_KBS_Biomass_Thermogravimetric' => 'Info KBS Biomass Thermogravimetric',
'Info_KBS_Biomass_Ulitmate' => 'Info KBS Biomass Ulitmate',
'Info_KBS_Biomass_Uses' => 'Info KBS Biomass Uses',
'Info_KBS_Food_Nutrient_Composition' => 'Info KBS Food Nutrient Composition',
'Info_KBS_Food_Nutrient_Minerals' => 'Info KBS Food Nutrient Minerals',
'Info_KBS_Food_Nutrient_Vitamins' => 'Info KBS Food Nutrient Vitamins',
'Info_KBS_General' => 'Info KBS General',
'Info_KBS_General_Growth_Cycle' => 'Info KBS General Growth Cycle',
'Info_KBS_General_Growth_Habit' => 'Info KBS General Growth Habit',
'Info_KBS_General_Parts' => 'Info KBS General Parts',
'Info_KBS_General_Parts_Used' => 'Info KBS General Parts Used',
'Info_KBS_General_Type' => 'Info KBS General Type',
'Info_KBS_General_Usage' => 'Info KBS General Usage',
'Info_KBS_SocioEconomy_Human' => 'Info KBS SocioEconomy Human',
'Info_KBS_SocioEconomy_Infrastructure' => 'Info KBS SocioEconomy Infrastructure',
'Info_KBS_SocioEconomy_Market' => 'Info KBS SocioEconomy Market',
'Info_KBS_SocioEconomy_Price' => 'Info KBS SocioEconomy Price',
'Info_KBS_SocioEconomy_Subsidy' => 'Info KBS SocioEconomy Subsidy',
'Info_KBS_SocioEconomy_Water_Source' => 'Info KBS SocioEconomy Water Source',
'KBS_Agro_Agroecology' => 'KBS Agro Agroecology',
'KBS_Agro_Agronomic_Practices' => 'KBS Agro Agronomic Practices',
'KBS_Agro_Cropping_System' => 'KBS Agro Cropping System',
'KBS_Agro_Fertiliser' => 'KBS Agro Fertiliser',
'KBS_Agro_Pathology' => 'KBS Agro Pathology',
'KBS_Agro_Resist_Tolerance' => 'KBS Agro Resist Tolerance',
'KBS_Agro_Season' => 'KBS Agro Season',
'KBS_Aquacrop' => 'KBS Aquacrop',
'KBS_Biomass_Output' => 'KBS Biomass Output',
'KBS_Biomass_Proximate' => 'KBS Biomass Proximate',
'KBS_Biomass_Thermogravimetric' => 'KBS Biomass Thermogravimetric',
'KBS_Biomass_Ulitmate' => 'KBS Biomass Ulitmate',
'KBS_Biomass_Uses' => 'KBS Biomass Uses',
'KBS_Crop_CRO_File' => 'KBS Crop CRO File',
'KBS_Crop_Diseases' => 'KBS Crop Diseases',
'KBS_Crop_Germplasm' => 'KBS Crop Germplasm',
'KBS_Crop_Institute' => 'KBS Crop Institute',
'KBS_Crop_Local_Name' => 'KBS Crop Local Name',
'KBS_Crop_Pests' => 'KBS Crop Pests',
'KBS_Crop_Stat' => 'KBS Crop Stat',
'KBS_Crop_Synonyms' => 'KBS Crop Synonyms',
'KBS_Crop_TTSR' => 'KBS Crop TTSR',
'KBS_Crop_Vernacular_Name' => 'KBS Crop Vernacular Name',
'KBS_Crop_Weeds' => 'KBS Crop Weeds',
'KBS_Crop_Where_Researched' => 'KBS Crop Where Researched',
'KBS_Crop_Where_UnderUtilised' => 'KBS Crop Where UnderUtilised',
'KBS_Food_Nutrient_Composition' => 'KBS Food Nutrient Composition',
'KBS_Food_Nutrient_Minerals' => 'KBS Food Nutrient Minerals',
'KBS_Food_Nutrient_Vitamins' => 'KBS Food Nutrient Vitamins',
'KBS_Food_Preparation' => 'KBS Food Preparation',
'KBS_General' => 'KBS General',
'KBS_General_Growth_Cycle' => 'KBS General Growth Cycle',
'KBS_General_Growth_Habit' => 'KBS General Growth Habit',
'KBS_General_Parts' => 'KBS General Parts',
'KBS_General_Parts_Used' => 'KBS General Parts Used',
'KBS_General_Type' => 'KBS General Type',
'KBS_General_Usage' => 'KBS General Usage',
'KBS_Global_Authors' => 'KBS Global Authors',
'KBS_Global_Country_LatLong' => 'KBS Global Country LatLong',
'KBS_Global_Diseasess' => 'KBS Global Diseasess',
'KBS_Global_GeoNames' => 'KBS Global GeoNames',
'KBS_Global_Institute' => 'KBS Global Institute',
'KBS_Global_Parts_ID' => 'KBS Global Parts ID',
'KBS_Global_Pests' => 'KBS Global Pests',
'KBS_Global_Weeds' => 'KBS Global Weeds',
'KBS_localname_trial' => 'KBS Localname Trial',
'KBS_Metadata' => 'KBS Metadata',
'KBS_Parameter_Accuracy' => 'KBS Parameter Accuracy',
'KBS_Parameter_Geo' => 'KBS Parameter Geo',
'KBS_Parameter_Images' => 'KBS Parameter Images',
'KBS_Parameter_Notes' => 'KBS Parameter Notes',
'KBS_Parameter_References' => 'KBS Parameter References',
'KBS_SocioEconomy_Human' => 'KBS SocioEconomy Human',
'KBS_SocioEconomy_Infrastructure' => 'KBS SocioEconomy Infrastructure',
'KBS_SocioEconomy_Market' => 'KBS SocioEconomy Market',
'KBS_SocioEconomy_Price' => 'KBS SocioEconomy Price',
'KBS_SocioEconomy_Subsidy' => 'KBS SocioEconomy Subsidy',
'KBS_SocioEconomy_Water_Source' => 'KBS SocioEconomy Water Source');

function SetUpUserAuthorization()
{
    global $usersIds;
    global $grants;
    global $appGrants;
    global $dataSourceRecordPermissions;
    $userAuthorizationStrategy = new HardCodedUserAuthorization(new UserIdentitySessionStorage(GetIdentityCheckStrategy()), new HardCodedUserGrantsManager($grants, $appGrants), $usersIds);
    GetApplication()->SetUserAuthorizationStrategy($userAuthorizationStrategy);

GetApplication()->SetDataSourceRecordPermissionRetrieveStrategy(
    new HardCodedDataSourceRecordPermissionRetrieveStrategy($dataSourceRecordPermissions));
}

function GetIdentityCheckStrategy()
{
    global $users;
    return new SimpleIdentityCheckStrategy($users, '');
}

?>